
package hr.tecaj;

import java.awt.Color;

import java.io.File;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author damir
 */
public class FormaGraf extends javax.swing.JFrame {
    private JFreeChart graf;
    ChartPanel panel;

    /** Creates new form Graf */
    public FormaGraf() {
        initComponents();
        kreirajGraf();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }//GEN-END:initComponents

    private void kreirajGraf() {
        final NumberAxis rangeAxis = new NumberAxis("Y-Axis");
        rangeAxis.setRange(7,8);
        rangeAxis.setTickUnit(new NumberTickUnit(0.05));
       // rangeAxis.setTickUnit(new NumberTickUnit(0.05));
       final XYSeries god2008 = new XYSeries("2008");
        god2008.add(1, 7.228114);
        god2008.add(4, 7.231443);
        god2008.add(7, 7.193783);
        god2008.add(10, 7.085424);
        god2008.add(12, 7.098951);
        
        final XYSeries god2010 = new XYSeries("2010");
         god2010.add(1, 7.252208);
         god2010.add(4, 7.225134);
         god2010.add(7, 7.163396);
         god2010.add(10, 7.269164);
         god2010.add(12, 7.353646);
        
        final XYSeries god2013 = new XYSeries("2013");
        god2013.add(1, 7.523954);
        god2013.add(4, 7.563114);
        god2013.add(7, 7.421461);
        god2013.add(10, 7.579953);
        god2013.add(12, 7.603049);
        
       // DefaultCategoryDataset podaci = new DefaultCategoryDataset();
       final XYSeriesCollection podaci = new XYSeriesCollection();
        /*podaci.addValue(7.085424, "Teèaj", "2008");
        podaci.addValue(7.19718, "Teèaj", "2009");
        podaci.addValue(7.163396, "Teèaj", "2010");
        podaci.addValue(7.324715, "Teèaj", "2011");
        podaci.addValue(7.368511, "Teèaj", "2012");
        podaci.addValue(7.421461, "Teèaj", "2013");
        podaci.addValue(7.540866, "Teèaj", "2014");*/
        podaci.addSeries(god2008);
        podaci.addSeries(god2010);
        podaci.addSeries(god2013);
        graf =
            ChartFactory.createXYLineChart("Teèaj kroz godine", "Godina", "Teèaj", podaci,
                                         PlotOrientation.VERTICAL, true, true, false);

        /* Step -3 : Write line chart to a file */
        int width = 640; /* Width of the image */
        int height = 480; /* Height of the image */
        /* File lineChart=new File("line_Chart_example.png");
                         ChartUtilities.saveChartAsPNG(lineChart,lineChartObject,width,height); */
        //graf.getCategoryPlot().setBackgroundPaint(Color.blue);
       // CategoryPlot xyPlot = (CategoryPlot) graf.getPlot();
       XYPlot xyPlot = (XYPlot) graf.getPlot();
        xyPlot.setRangeAxis(rangeAxis);
               // xyPlot.setDomainCrosshairVisible(true);
                //xyPlot.setRangeCrosshairVisible(true);
        panel = new ChartPanel(graf);
        panel.setSize(400, 300);
        jPanel1.add(panel);
        //setContentPane(panel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaGraf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
