
package hr.tecaj;

import java.io.IOException;

import java.net.URL;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author damirdina;
 */
public class MainForm extends javax.swing.JFrame {
    // Fiksni dio URL za navigaciju to tecajeva na dan
    private String linkPrefiks = "http://www.hnb.hr/tecajn/";
    // Regular expression parametri, traze se samo decimalni brojevi
    private String regexp = "(\\d+)(\\,){1}(\\d)+";
    private Pattern maska = Pattern.compile(regexp, Pattern.CASE_INSENSITIVE);
    private String valuta;
    private String godina;
    private List<String> listaMjeseci = new ArrayList();
    private List<Tecaj> listaTecajeva = new ArrayList();

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtfMjeseci = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfGodina = new javax.swing.JTextField();
        jftValuta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HNB teèaj eura");

        jButton1.setMnemonic('P');
        jButton1.setText("Povuci");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtfMjeseci.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfMjeseci.setText("01,02,03,04,05,06,07,08,09,10,11,12");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(50, 105, 195));
        jLabel3.setText("Mjeseci");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 105, 195));
        jLabel2.setText("Godina");

        jtfGodina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfGodina.setText("2008");

        jftValuta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jftValuta.setText("EMU");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 105, 195));
        jLabel1.setText("Valuta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfGodina)
                        .addComponent(jftValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfMjeseci, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(435, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMjeseci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setMnemonic('I');
        jButton2.setText("Izlaz");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        valuta = jftValuta.getText().trim();
        godina = jtfGodina.getText().trim().substring(2);
        Scanner scan = new Scanner(jtfMjeseci.getText().trim()).useDelimiter(",");
        while (scan.hasNext()) {
            listaMjeseci.add(scan.next());
        }
        povuciLinkoveTecajeva();
        izvuciTecajNaDan();
      /*  for (Tecaj tecaj : listaTecajeva) {
            Pomocna.ispis(tecaj);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void povuciLinkoveTecajeva() {
        String puniLink;
        
        for (String mjesec : listaMjeseci) {

            try {
                Document dokument =
                    Jsoup.connect("http://www.hnb.hr/tecajn/h" + mjesec + godina + ".htm").userAgent("Mozilla").get();
                Elements linkovi = dokument.select("a[href]");
                for (Element link : linkovi) {
                    puniLink = linkPrefiks + link.attr("href").substring(2, link.attr("href").length());                   
                    Tecaj tecaj = new Tecaj();
                    tecaj.setMjesec(Integer.parseInt(mjesec));
                    tecaj.setDan(Integer.parseInt(puniLink.substring(linkPrefiks.length() + 1, linkPrefiks.length() + 3)));
                    tecaj.setLink(puniLink);
                    listaTecajeva.add(tecaj);
                    //System.out.println(puniLink);
                }
            } catch (IOException e) {
                Pomocna.porukaError(this.getContentPane(), e.getMessage());
            }
        }
    }

    private void izvuciTecajNaDan() {
        String tecajnaLista;
        String tecajValute;

        for (Tecaj tecaj : listaTecajeva) {
            try {
                Document dokument = Jsoup.parse(new URL(tecaj.getLink()).openStream(), "Cp1250", tecaj.getLink());
                Elements linkovi = dokument.select("pre");
                for (Element link : linkovi) {
                    tecajnaLista = link.html();
                    tecajValute =
                        tecajnaLista.substring(tecajnaLista.indexOf(valuta),
                                               tecajnaLista.indexOf("\n", tecajnaLista.indexOf(valuta)));              
                    izvuciTecaj(tecaj, tecajValute);
                }
            } catch (IOException e) {
                Pomocna.porukaError(this.getContentPane(), e.getMessage());
            }
        }
    }

    private void izvuciTecaj(Tecaj tecaj, String tecajValute) {
        String tecajTmp;
        int pozicija = 1;
        Matcher m = maska.matcher(tecajValute);
        while (m.find()) {
            //System.out.println(m.group());
            tecajTmp = m.group();
            if (pozicija == 1) {
                tecaj.setKupovni(Pomocna.stringToBigDecimal(tecajTmp));
            } else if (pozicija == 2) {
                tecaj.setSrednji(Pomocna.stringToBigDecimal(tecajTmp));
            } else {
                tecaj.setProdajni(Pomocna.stringToBigDecimal(tecajTmp));
            }
            pozicija++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jftValuta;
    private javax.swing.JTextField jtfGodina;
    private javax.swing.JTextField jtfMjeseci;
    // End of variables declaration//GEN-END:variables

}
